export enum PermissionEnum {
  READ_USER = 'READ_USER',
  EDIT_USER = 'EDIT_USER',
  CREATE_USER = 'CREATE_USER',
  DELETE_USER = 'DELETE_USER',
  READ_ARTICLE = 'READ_ARTICLE',
  EDIT_ARTICLE = 'EDIT_ARTICLE',
  CREATE_ARTICLE = 'CREATE_ARTICLE',
  DELETE_ARTICLE = 'DELETE_ARTICLE',
}
